# Generated by Django 5.1.4 on 2025-01-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TestSerializerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("is_something", models.BooleanField()),
                ("email", models.CharField(max_length=256)),
                ("slug", models.CharField(max_length=64)),
                ("real", models.FloatField()),
                ("password", models.CharField(max_length=50)),
                ("generated", models.CharField(max_length=256)),
            ],
        ),
    ]
